name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image with version tagging
      - name: Build Docker image with tags
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          TAG=${{ github.ref_name }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .

      # Push the Docker image with tags
      - name: Push Docker image with tags
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          TAG=${{ github.ref_name }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG
